{% set name = "orbit-ml" %}
{% set version = "1.1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orbit-ml-{{ version }}.tar.gz
  sha256: b846f62b434ee2e17f6bc55c93beb4f8598e54536ea12172786ea57b6ab9d087

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - pytest
    - python >=3.9, <= 3.12
    - numpy >=1.26.4
    - cmdstanpy >=1.2.1
    - importlib_resources >=6.4.0
  run:
    - arviz >=0.17.1
    - cmdstanpy >=1.2.1
    - importlib_resources >=6.4.0
    - ipywidgets
    - matplotlib >=3.8.3
    - numpy >=1.26.4
    - pandas >=2.2.1
    - pyro-ppl >=1.9.0
    - scipy >=1.12.0
    - seaborn >=0.13.2
    - setuptools >=42
    - statsmodels >=0.14.1
    - torch >=2.2.1
    - tqdm >=4.66.2

test:
  imports:
    - orbit
    - orbit.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://orbit-ml.readthedocs.io/en/stable/
  summary: Orbit is a package for bayesian time series modeling and inference.
  license: Apache-2.0
  license_file: LICENSE
  description: |2

    <a href="https://github.com/uber/orbit">
      <img src="https://raw.githubusercontent.com/uber/orbit/dev/docs/img/orbit-banner.png" alt="Orbit banner" />
    </a>

    Orbit is a Python package for Bayesian time series forecasting and inference. 
    It provides a familiar and intuitive initialize-fit-predict interface for time 
    series tasks, while utilizing probabilistic programming languages under the hood.

    For details, check out our documentation and tutorials:
    - HTML (stable): https://orbit-ml.readthedocs.io/en/stable/
    - HTML (latest): https://orbit-ml.readthedocs.io/en/latest/

    Currently, it supports concrete implementations for the following models:

    -  Exponential Smoothing (ETS)
    -  Local Global Trend (LGT)
    -  Damped Local Trend (DLT)
    -  Kernel Time-based Regression (KTR)

    It also supports the following sampling/optimization methods for model estimation/inferences:

    -  Markov-Chain Monte Carlo (MCMC) as a full sampling method
    -  Maximum a Posteriori (MAP) as a point estimate method
    -  Variational Inference (VI) as a hybrid-sampling method on approximate
      distribution


    PyPI: [https://pypi.org/project/orbit-ml/](https://pypi.org/project/orbit-ml/)

  doc_url: https://orbit-ml.readthedocs.io/en/stable/
  dev_url: https://github.com/uber/orbit

extra:
  recipe-maintainers:
    - edwinnglabs
    - sugatoray
