{% set name = "orbit-ml" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orbit-ml-{{ version }}.tar.gz
  sha256: 7a8b15661805446ad19239bd33676e43f1d7f73291f108372bcad78f0aeffe8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.7, <=3.8
    - numpy >=1.18.2, <=1.22.2
  run:
    - python >=3.7, <=3.8
    - numpy >=1.18.2, <=1.22.2
    - arviz
    - matplotlib-base >=3.3.2
    - numpy >=1.18.2
    - pandas >=1.0.3
    - pyro-ppl >=1.4.0
    - pystan ==2.19.1.1
    - scipy >=1.4.1
    - seaborn >=0.10.0
    - statsmodels >=0.11.1
    - pytorch
    - tqdm

test:
  imports:
    - orbit
    - orbit.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://orbit-ml.readthedocs.io/en/stable/
  summary: Orbit is a package for bayesian time series modeling and inference.
  license: Apache-2.0
  license_file: LICENSE
  description: |

    <a href="https://github.com/uber/orbit">
      <img src="https://raw.githubusercontent.com/uber/orbit/dev/docs/img/orbit-banner.png" alt="Orbit banner" />
    </a>

    Orbit is a Python package for Bayesian time series forecasting and inference. 
    It provides a familiar and intuitive initialize-fit-predict interface for time 
    series tasks, while utilizing probabilistic programming languages under the hood.

    For details, check out our documentation and tutorials:
    - HTML (stable): https://orbit-ml.readthedocs.io/en/stable/
    - HTML (latest): https://orbit-ml.readthedocs.io/en/latest/

    Currently, it supports concrete implementations for the following models:

    -  Exponential Smoothing (ETS)
    -  Local Global Trend (LGT)
    -  Damped Local Trend (DLT)
    -  Kernel Time-based Regression (KTR)

    It also supports the following sampling/optimization methods for model estimation/inferences:

    -  Markov-Chain Monte Carlo (MCMC) as a full sampling method
    -  Maximum a Posteriori (MAP) as a point estimate method
    -  Variational Inference (VI) as a hybrid-sampling method on approximate
      distribution


    PyPI: [https://pypi.org/project/orbit-ml/](https://pypi.org/project/orbit-ml/)

  doc_url: https://orbit-ml.readthedocs.io/en/stable/
  dev_url: https://github.com/uber/orbit

extra:
  recipe-maintainers:
    - sugatoray
