{% set name = "orbit-ml" %}
{% set version = "1.1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/orbit-ml-{{ version }}.tar.gz
  sha256: 5843f7748036f39bb4d95af07aadca5e8a2f5f2de6f5eda16cf4a73ad8cc3bb3

# build:
#   number: 0
#   noarch: python
# script: 
#   - TBB_CXX_TYPE=gcc
#   - python -c "import sys; print(sys.version)"
#   - {{ PYTHON }} -m pip install . -vv
# entry_points:
#   - install_cmdstan = cmdstanpy.install_cmdstan:main
#   - install_cxx_toolchain = cmdstanpy.install_cxx_toolchain:main

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
    - numpy >=1.18.2
    - cmdstanpy >=1.0.4
  run:
    - python >=3.7
    - numpy >=1.18
    - pandas >=1.0.3
    - matplotlib-base >=3.3.2
    - scipy >=1.4.1
    - pytorch >=1.11.0
    - cmdstanpy >=1.0.4
    - pyro-ppl >=1.4.0
    - seaborn >=0.10.0
    - statsmodels >=0.11.1
    - arviz
    - tqdm >=4.36.1
    

test:
  imports:
    - orbit
    - orbit.constants
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://orbit-ml.readthedocs.io/en/stable/
  summary: Orbit is a package for bayesian time series modeling and inference.
  license: Apache-2.0
  license_file: LICENSE
  description: |

    <a href="https://github.com/uber/orbit">
      <img src="https://raw.githubusercontent.com/uber/orbit/dev/docs/img/orbit-banner.png" alt="Orbit banner" />
    </a>

    Orbit is a Python package for Bayesian time series forecasting and inference. 
    It provides a familiar and intuitive initialize-fit-predict interface for time 
    series tasks, while utilizing probabilistic programming languages under the hood.

    For details, check out our documentation and tutorials:
    - HTML (stable): https://orbit-ml.readthedocs.io/en/stable/
    - HTML (latest): https://orbit-ml.readthedocs.io/en/latest/

    Currently, it supports concrete implementations for the following models:

    -  Exponential Smoothing (ETS)
    -  Local Global Trend (LGT)
    -  Damped Local Trend (DLT)
    -  Kernel Time-based Regression (KTR)

    It also supports the following sampling/optimization methods for model estimation/inferences:

    -  Markov-Chain Monte Carlo (MCMC) as a full sampling method
    -  Maximum a Posteriori (MAP) as a point estimate method
    -  Variational Inference (VI) as a hybrid-sampling method on approximate
      distribution


    PyPI: [https://pypi.org/project/orbit-ml/](https://pypi.org/project/orbit-ml/)

  doc_url: https://orbit-ml.readthedocs.io/en/stable/
  dev_url: https://github.com/uber/orbit

extra:
  recipe-maintainers:
    - edwinnglabs
    - sugatoray
    # maintainers from upstream repository
    - edwinnglabs
